apiVersion: apps/v1
kind: Deployment
metadata:
  name: bbxp-web-app
  labels:
    app: bbxp-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bbxp-web-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: bbxp-web-app
    spec:
      containers:
      - name: bbxp-web-mvc
        image: <MVCIMAGE>
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
      - name: bbxp-web-api
        image: <APIIMAGE>
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: bbxp-web-app-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: bbxp-web-app
