apiVersion: apps/v1
kind: Deployment
metadata:
  name: bbxp-platform
  labels:
    app: bbxp-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bbxp-web-app-pod
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: bbxp-web-app-pod
    spec:
      containers:
      #- name: bbxp-web-mvc-container
      #  image: <MVCIMAGE>
      #  ports:
      #  - containerPort: 8080
      #  resources:
      #    requests:
      #      cpu: "0.25"
      #    limits:
      #      cpu: "0.5"
      #  volumeMounts:
      #  - mountPath: "/data"
      #    name: bbxp-web-pvc
      - name: bbxp-web-api-container
        image: <APIIMAGE>
        ports:
        - containerPort: 80
      #volumeClaimTemplates:
      #- metadata:
      #      name: bbxp-web-pvc
      #  spec:
      #      accessModes:
      #      - ReadWriteOnce
      #      resources:
      #          requests:
      #              storage: 2Gi
      #      storageClassName: do-block-storage
---
apiVersion: v1
kind: Service
metadata:
  name: bbxp-web-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: bbxp-web-app-pod
