apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bbxp-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - jarredcapellman.com    
    secretName: echo-tls
  rules:
    - host: jarredcapellman.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: bbxp-platform
                port:
                  number: 80