name: Build and Push to GCR and then deploy to Cloud Run

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Container
      run: dotnet publish /home/runner/work/bbxp/bbxp.web.api/bbxp.web.api.csproj -r linux-x64 /t:PublishContainer -c Release

    - name: Tag Container
      run: docker tag bbxp-web-api:latest us-central1-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/bbxp-web-api/bbxp-web-api:latest
    
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        project_id: '${{ secrets.GCP_PROJECT_ID }}'
        credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}"

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Configure Docker Auth
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Push Container to GCP
      run: docker push us-central1-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/bbxp-web-api/bbxp-web-api:latest

    - name: Deploy to CLoud Run
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: 'bbxp-web-api'
        image: us-central1-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/bbxp-web-api/bbxp-web-api
