name: Build and Push to GCR and then deploy to Cloud Run

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    env:
        FILEPATH_API: '/home/runner/work/bbXP/bbXP/bbxp.web.api/bbxp.web.api.csproj'
        FILEPATH_MVC: '/home/runner/work/bbXP/bbXP/bbxp.web.mvc/bbxp.web.mvc.csproj'
        FOLDER_API: 'bbxp-webapi'
        FOLDER_MVC: 'bbxp-mvc'
        TAG_API: 'bbxp-web-api'
        TAG_MVC: 'bbxp-web-mvc'
        PUBLISH_FLAGS: '-r linux-x64 /t:PublishContainer -c Release'
        VERSION: '2024.7.${{github.RUN_NUMBER}}'

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore API dependencies
      run: dotnet restore ${{env.FILEPATH_API}}
      
    - name: Restore MVC dependencies
      run: dotnet restore ${{env.FILEPATH_MVC}}

    - name: Build API Container
      run: dotnet publish ${{env.FILEPATH_API}} ${{env.PUBLISH_FLAGS}} /p:Version='${{env.VERSION}}'

    - name: Tag API Container
      run: docker tag ${{env.TAG_API}}:latest us-central1-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/${{env.FOLDER_API}}/${{env.TAG_API}}:latest

    - name: Build MVC Container
      run: dotnet publish ${{env.FILEPATH_MVC}} ${{env.PUBLISH_FLAGS}} /p:Version='${{env.VERSION}}'

    - name: Tag MVC Container
      run: docker tag ${{env.TAG_MVC}}:latest us-central1-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/${{env.FOLDER_MVC}}/${{env.TAG_MVC}}:latest
    
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        project_id: '${{ secrets.GCP_PROJECT_ID }}'
        credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}"

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Configure Docker Auth
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Push API Container to GCP
      run: docker push us-central1-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/${{env.FOLDER_API}}/${{env.TAG_API}}:latest

    - name: Deploy API to CLoud Run
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: ${{env.TAG_API}}
        image: us-central1-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/${{env.FOLDER_API}}/${{env.TAG_API}}

    - name: Push MVC Container to GCP
      run: docker push us-central1-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/${{env.FOLDER_MVC}}/${{env.TAG_MVC}}:latest

    - name: Deploy MVC to CLoud Run
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: ${{env.TAG_MVC}}
        image: us-central1-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/${{env.FOLDER_MVC}}/${{env.TAG_MVC}}
